# $HOME/.bash_profile

# load bashrc
if [ -f $HOME/.bashrc ]; then
  source $HOME/.bashrc
fi

# Load all files from .shell/login.d directory
if [ -d $HOME/.shellrc/login.d ]; then
    shopt -s nullglob
    
    for file in $HOME/.shellrc/login.d/*.sh; do
        source $file
    done
  
    shopt -u nullglob
fi