# $HOME/.zshrc

# load all files from .shellrc/zshrc.d
if [ -d $HOME/.shellrc/zshrc.d ]; then
	for file in $HOME/.shellrc/zshrc.d/*.zsh; do
		source $file
	done
fi

# load all files from .shellrc/rc.d
if [-d $HOME/.shellrc/rc.d ]; then
	for file in $HOME/.shellrc/rc.d/*.sh; do
		source $file
	done
fi
